import Document, { Html, Head, Main, NextScript } from 'next/document'

import { ColorModeScript } from "@chakra-ui/react"
import theme from '@/theme/index'

export default class MyDocument extends Document {
    render() {
        return(
            <Html lang="en">
                <Head>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
                <body>
                    <ColorModeScript initialColorMode={theme.config.initialColorMode} />
                    <Main />
                    <NextScript />
                </body>
            </Html>
        )
    }
}