import Head from 'next/head'
import { getSession } from 'next-auth/client'
import { Text } from '@chakra-ui/react'

export default function AdminPage({ session }) {
    if(!session.role == 'ADMIN') return <Text color="red.500">Not Allowed</Text>

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    )
}

/**
* 
* @param {import('next').GetServerSidePropsContext} context
* @returns
*/
export async function getServerSideProps(context) {

    return {
        props: {
            session: await getSession(context)
        }
    }
}
